# Generated by Django 5.0.2 on 2024-03-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appflk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='categoria',
        ),
        migrations.AddField(
            model_name='libro',
            name='categorias',
            field=models.ManyToManyField(to='Appflk.categoria'),
        ),
    ]
